### PR TITLE
Make uadetector compatible with udger.com database

### PR DESCRIPTION
**Pull request by HaraldWalker**
Added options in UADetectorServiceFactory to specify the data and version url, including custom fallback database.
Fixed incompatibility issues with current udget.com UAS database including some minor changes to the embedded uas.xml database.

### CODE REVIEW

**Comment by HaraldWalker** [comment]
Sorry, didn't see the tests in net.sf.uadetector.json. Don't know what the purpose of that module is. 
Don't understand yet the failing core tests on buildhive. When running those tests within the IDE both are passing.

**Comment by dfadid** [comment]
hey , as you can see there are two failing tests in net.sf.uadetector:uadetector-core as well

**Comment by before** [comment]
I removed some unnecessary tabs and whitespaces and merged it. Thank you for preparing these changes.

**Comment by HaraldWalker** [comment]
Unless Jaroslav allows you to bundle a version of the commercial database (e.g. reduced or X months old), the resource project that in the past included the latest version of the uas.xml database lost its purpose. The factory class could be moved into core and it would simply the project code base and structure.

**Comment by HaraldWalker** [comment]
@before When you release these changes as new version, a lot of the current documentation will need updates including new code examples. I'd be happy to help with that.

**Pull request closed without merging**
